# Generated by Django 2.0.6 on 2018-06-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transpCoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teste',
            options={'verbose_name_plural': 'teste'},
        ),
    ]
