# Generated by Django 2.0.6 on 2018-06-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transpCoreApp', '0004_paragens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragens',
            old_name='typ',
            new_name='type',
        ),
    ]
