# Generated by Django 2.0.6 on 2018-06-11 05:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transpCoreApp', '0005_auto_20180602_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='c6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('codrota', models.CharField(max_length=50)),
                ('rota', models.CharField(max_length=50)),
                ('carreira', models.CharField(max_length=50)),
                ('viauso', models.CharField(max_length=50)),
                ('nomecorred', models.CharField(max_length=50)),
                ('codoperado', models.CharField(max_length=50)),
                ('codbairro', models.CharField(max_length=50)),
                ('coddistrit', models.CharField(max_length=50)),
                ('codvia', models.CharField(max_length=50)),
                ('shape_leng', models.FloatField()),
                ('codseccao', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='c9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('codrota', models.CharField(max_length=50)),
                ('rota', models.CharField(max_length=50)),
                ('carreira', models.CharField(max_length=50)),
                ('viauso', models.CharField(max_length=50)),
                ('nomecorred', models.CharField(max_length=50)),
                ('codoperado', models.CharField(max_length=50)),
                ('codbairro', models.CharField(max_length=50)),
                ('coddistrit', models.CharField(max_length=50)),
                ('codvia', models.CharField(max_length=50)),
                ('shape_leng', models.FloatField()),
                ('codseccao', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
